# Generated by Django 3.1.5 on 2021-02-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mahsulot xususiyati')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Narxi')),
                ('addTime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Q'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['addTime'],
            },
        ),
    ]
