# Generated by Django 3.1.5 on 2021-02-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_auto_20210201_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Narxi'),
        ),
    ]
