# Generated by Django 3.1.5 on 2021-02-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_auto_20210201_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name="Do'kon"),
        ),
    ]
