# Generated by Django 3.1.5 on 2021-01-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_auto_20210111_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
