# Generated by Django 3.1.5 on 2021-01-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20210111_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='created_at',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='toy',
            name='upteted_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
