# Generated by Django 3.1.5 on 2021-02-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0006_auto_20210125_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
